name: BandePlugin
version: ${project.version}
main: dk.simonwinther.MainPlugin
api-version: 1.16
authors: [simonsejse]
description: Et avanceret bande plugin
depend: [WorldEdit, WorldGuard, Citizens, Vault]
website: simon-winther.dk
commands:
  bande:
    aliases: b
